Sym path compat and errors
microsoft/pdblister pull request #8
Opened 2022-10-26 00:02 UTC by dwattttt

Case mismatch in the symbol server path means `srv*` causes pdblister to fail to proceed. There's no reason to fail here, this PR normalizes the `srv` components case before checking.

This PR also adds clearer error messages around this, and makes anyhow show the cause of failures to download.

2022-10-26 00:03 UTC, dwattttt commented
@microsoft-github-policy-service agree [company="default"]

2022-10-26 00:04 UTC, dwattttt commented
@microsoft-github-policy-service agree

2022-11-08 18:59 UTC, DrChat requested changes

2022-11-08 18:59 UTC, DrChat commented on src/symsrv.rs
> +                if "SRV" == x.to_ascii_uppercase() {
```suggestion
                if x.eq_ignore_ascii_case("SRV") {
```

2022-11-08 20:42 UTC, DrChat approved these changes

2022-11-08 20:51 UTC, comcma approved these changes

2022-11-08 20:52 UTC, merged